version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: [name-dash]-webserver
    working_dir: /application
    volumes:
      - nfsmount:/application
      - ./config/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "[number-int]0:80"

  php-fpm:
    build: config/docker/php-fpm
    container_name: [name-dash]-php-fpm
    working_dir: /application
    volumes:
      - nfsmount:/application
      - ./config/docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

  mysql:
    image: mysql:5.7
    container_name: [name-dash]-mysql
    working_dir: /application
    volumes:
    - nfsmount:/application
    environment:
    - MYSQL_ROOT_PASSWORD=[name-dash]
    - MYSQL_DATABASE=[name-dash]
    - MYSQL_USER=[name-dash]
    - MYSQL_PASSWORD=[name-dash]
    ports:
    - "[number-int]1:3306"

  mysql_test:
    image: mysql:5.7
    container_name: [name-dash]-mysql-test
    working_dir: /application
    volumes:
      - nfsmount:/application
    environment:
      - MYSQL_ROOT_PASSWORD=[name-dash]
      - MYSQL_DATABASE=[name-dash]_test
      - MYSQL_USER=[name-dash]
      - MYSQL_PASSWORD=[name-dash]
    ports:
      - "[number-int]7:3306"

  robotfw:
    image: nomasolutions/robotfw:latest
    container_name: [name-dash]-robotfw
    working_dir: /robot
    volumes:
      - ./tests/robot:/robot

  nodejs:
    build: ./config/docker/nodejs
    container_name: [name-dash]-nodejs
    working_dir: /application
    ports:
      - [number-int]6:4200
    volumes:
      - nfsmount:/application

volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/Users/${USER}/projekty/nomasolutions/ns0[number-int]"
