version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: pif-webserver
    working_dir: /application
    volumes:
      - nfsmount:/application
      - ./config/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "11360:80"

  php-fpm:
    build: config/docker/php-fpm
    container_name: pif-php-fpm
    working_dir: /application
    volumes:
      - nfsmount:/application
      - ./config/docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

  mysql:
    image: mysql:5.7
    container_name: pif-mysql
    working_dir: /application
    volumes:
    - nfsmount:/application
    environment:
    - MYSQL_ROOT_PASSWORD=pif
    - MYSQL_DATABASE=pif
    - MYSQL_USER=pif
    - MYSQL_PASSWORD=pif
    ports:
    - "11361:3306"

  mysql_test:
    image: mysql:5.7
    container_name: pif-mysql-test
    working_dir: /application
    volumes:
      - nfsmount:/application
    environment:
      - MYSQL_ROOT_PASSWORD=pif
      - MYSQL_DATABASE=pif_test
      - MYSQL_USER=pif
      - MYSQL_PASSWORD=pif
    ports:
      - "11367:3306"

  mongodb:
    image: 'bitnami/mongodb:latest'
    container_name: pif-mongodb
    labels:
      kompose.service.type: nodeport
    ports:
    - "11362:27017"
    environment:
    - AUTH=no
    - MONGODB_ROOT_PASSWORD=pif
    - MONGODB_USERNAME=pif
    - MONGODB_PASSWORD=pif
    - MONGODB_DATABASE=pif
    volumes:
    - nfsmount:/application

  rabbitmq:
    build: config/docker/rabbitmq
    container_name: pif-rabbit
    working_dir: /application
    ports:
      - 11363:15672
      - 11364:5672
      - 11365:15674
    volumes:
      - nfsmount:/application
      - ./config/docker/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./config/docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json

  robotfw:
    image: nomasolutions/robotfw:latest
    container_name: pif-robotfw
    working_dir: /robot
    volumes:
      - ./tests/robot:/robot

  nodejs:
    build: ./config/docker/nodejs
    container_name: pif-nodejs
    working_dir: /application
    ports:
      - 11366:4200
    volumes:
      - nfsmount:/application

volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/Users/${USER}/projekty/nomasolutions/ns01136"
